services:
  postgres:
    image: postgres:17.6-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - backend_files:/usr/src/app/files

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT}:3000

volumes:
  pg_data:
  backend_files: